---
server:
  port: 8080
  contextPath: /unistart
---
spring:
  profiles: default
datasource:
  university:
    url: jdbc:sqlserver://localhost:1433
    username: sa
    password: 123456
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.SQLServer2012Dialect