package com.unistart.entities;
// Generated Oct 1, 2017 10:03:30 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Block generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "Block", schema = "dbo", catalog = "University")
public class Block implements java.io.Serializable {

	private Integer id;
	private String blockName;
	private String description;
	private Boolean isActive;
	private Set<BlockOfMajor> blockOfMajors = new HashSet<BlockOfMajor>(0);
	private Set<BlockMajorUniversity> blockMajorUniversities = new HashSet<BlockMajorUniversity>(0);


	public Block() {
	}
	public Block(Integer id, String blockName ) {
		this.id = id;
		this.blockName = blockName;
	}

	public Block(Integer id, String blockName, String description, Boolean isActive,
			Set<BlockOfMajor> blockOfMajors, Set<BlockMajorUniversity> blockMajorUniversities) {
		this.id = id;
		this.blockName = blockName;
		this.description = description;
		this.isActive = isActive;
		this.blockOfMajors = blockOfMajors;
		this.blockMajorUniversities = blockMajorUniversities;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "BlockName")
	public String getBlockName() {
		return this.blockName;
	}

	public void setBlockName(String blockName) {
		this.blockName = blockName;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "block")
	public Set<BlockOfMajor> getBlockOfMajors() {
		return this.blockOfMajors;
	}

	public void setBlockOfMajors(Set<BlockOfMajor> blockOfMajors) {
		this.blockOfMajors = blockOfMajors;
	}


	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "block")
	public Set<BlockMajorUniversity> getBlockMajorUniversities() {
		return this.blockMajorUniversities;
	}

	public void setBlockMajorUniversities(Set<BlockMajorUniversity> blockMajorUniversities) {
		this.blockMajorUniversities = blockMajorUniversities;
	}
}
