package com.unistart.entities;
// Generated Oct 1, 2017 10:03:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * MajorMbti generated by hbm2java
 */
@Entity
@Table(name = "MajorMBTI", schema = "dbo", catalog = "University")
public class MajorMbti implements java.io.Serializable {

	private Integer id;
	private Major major;
	@JsonBackReference
	private Mbtitype mbtitype;
	private Boolean isActive;

	public MajorMbti() {
	}

	public MajorMbti(Integer id) {
		this.id = id;
	}

	public MajorMbti(Integer id, Major major, Mbtitype mbtitype, Boolean isActive) {
		this.id = id;
		this.major = major;
		this.mbtitype = mbtitype;
		this.isActive = isActive;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MajorId")
	public Major getMajor() {
		return this.major;
	}

	public void setMajor(Major major) {
		this.major = major;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MBTITypeID")
	public Mbtitype getMbtitype() {
		return this.mbtitype;
	}

	public void setMbtitype(Mbtitype mbtitype) {
		this.mbtitype = mbtitype;
	}

	@Column(name = "isActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
