package com.unistart.entities;
// Generated Oct 1, 2017 10:03:30 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIdentityReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Review generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "Review", schema = "dbo", catalog = "University")
public class Review implements java.io.Serializable {

	private Integer id;
	private University university;
	private Users users;
	private String title;
	private String description;
	private Integer starTeaching;
	private Integer starFacilities;
	private Integer starCare;
	private Integer starSocieties;
	private Integer starCareer;
	private Boolean isRecomment;
	private Boolean status;
	private Boolean isActive;
	private Set<ReviewLike> reviewLikes = new HashSet<ReviewLike>(0);

	public Review() {
	}

	public Review(Integer id, University university, Users users) {
		this.id = id;
		this.university = university;
		this.users = users;
	}

	public Review(Integer id, University university, Users users,String title, String description, Integer starTeaching,
			Integer starFacilities, Integer starCare, Integer starSocieties, Integer starCareer, Boolean isRecomment,
			Boolean status, Boolean isActive, Set<ReviewLike> reviewLikes) {
		this.id = id;
		this.university = university;
		this.users = users;
		this.title = title;
		this.description = description;
		this.starTeaching = starTeaching;
		this.starFacilities = starFacilities;
		this.starCare = starCare;
		this.starSocieties = starSocieties;
		this.starCareer = starCareer;
		this.isRecomment = isRecomment;
		this.status = status;
		this.isActive = isActive;
		this.reviewLikes = reviewLikes;
	}
	
	public Review(Integer id, String title, String description, Integer starTeaching,
			Integer starFacilities, Integer starCare, Integer starSocieties, Integer starCareer, Boolean isRecomment,
			Boolean status, Boolean isActive) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.starTeaching = starTeaching;
		this.starFacilities = starFacilities;
		this.starCare = starCare;
		this.starSocieties = starSocieties;
		this.starCareer = starCareer;
		this.isRecomment = isRecomment;
		this.status = status;
		this.isActive = isActive;
	}
	
	public Review(Integer id,University university, String title, String description,Boolean status, Boolean isActive) {
		this.id = id;
		this.university = university;
		this.title = title;
		this.description = description;
		this.status = status;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

    //@JsonIgnore
	@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "name")
	@JsonIdentityReference(alwaysAsId = true)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "UniversityId", nullable = false)
	public University getUniversity() {
		return this.university;
	}

	public void setUniversity(University university) {
		this.university = university;
	}

	//@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	
	@Column(name = "Title")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String desscription) {
		this.description = desscription;
	}

	@Column(name = "StarTeaching")
	public Integer getStarTeaching() {
		return this.starTeaching;
	}

	public void setStarTeaching(Integer starTeaching) {
		this.starTeaching = starTeaching;
	}

	@Column(name = "StarFacilities")
	public Integer getStarFacilities() {
		return this.starFacilities;
	}

	public void setStarFacilities(Integer starFacilities) {
		this.starFacilities = starFacilities;
	}

	@Column(name = "StarCare")
	public Integer getStarCare() {
		return this.starCare;
	}

	public void setStarCare(Integer starCare) {
		this.starCare = starCare;
	}

	@Column(name = "StarSocieties")
	public Integer getStarSocieties() {
		return this.starSocieties;
	}

	public void setStarSocieties(Integer starSocieties) {
		this.starSocieties = starSocieties;
	}

	@Column(name = "StarCareer")
	public Integer getStarCareer() {
		return this.starCareer;
	}

	public void setStarCareer(Integer starCareer) {
		this.starCareer = starCareer;
	}

	@Column(name = "IsRecomment")
	public Boolean getIsRecomment() {
		return this.isRecomment;
	}

	public void setIsRecomment(Boolean isRecomment) {
		this.isRecomment = isRecomment;
	}

	@Column(name = "Status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "review")
	public Set<ReviewLike> getReviewLikes() {
		return this.reviewLikes;
	}

	public void setReviewLikes(Set<ReviewLike> reviewLikes) {
		this.reviewLikes = reviewLikes;
	}

}
